spring:
  application:
    name: microservice-consumer-movice-feign
server:
  port: 8011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
